apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: fluxtest
resources:
- pod.yaml
- svc.yaml
nameSuffix: pod
configMapGenerator:
- name: config
  namespace: default
  data:
    choice: red
