apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeployment
  namespace: default
  labels:
    app: depmyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: testpod
      namespace: default
      labels:
        app: myapp
    spec:
      containers:
      - name: testpod
        image: amitkumarjo1994/testimage
        envFrom:
        - configMapRef:
            name: config
        imagePullSecrets:
        - name: secretregistry
