apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: default
  labels:
    app: myapp
spec:
  containers:
    - name: testpod
      image: amitkumarjo1994/testimage
      envFrom:
        - configMapRef:
            name: config
  imagePullSecrets:
    - name: secretregistry
